dataset:
  init_sensor_timeframes: [0, 10, 20, 30, 40, 50]
  n_fullstate_timeframes_per_chunk: 10
  n_samplings_per_chunk: 3
  resolution: [70, 120]
  n_sensors: 32
  sensor_generator: 'AroundCylinder'  # AroundCylinder | LHS
  embedding_generator: 'Voronoi'      # Voronoi | Mask
  seed: 1
  already_preloaded: true

architecture:
  n_channels: 2
  n_afno_layers: 4
  embedding_dim: 96
  block_size: 32
  dropout_rate: 0.1
  n_stacked_networks: 4
  from_checkpoint: null   # set to null to train from scratch

training:
  train_batch_size: 2
  val_batch_size: 1
  learning_rate: 1e-3
  a: 10.
  r: 0.01
  n_epochs: 1000
  patience: 50
  tolerance: 0.
  save_frequency: 1

predict:
  data: 'data/test/case0032'
  from_checkpoint: '.checkpoints/epoch10.pt'


