dataset:
  init_sensor_timeframes: [0, 5, 10, 15, 20]
  n_fullstate_timeframes_per_chunk: 1
  n_samplings_per_chunk: 1
  resolution: [140, 240]
  n_sensors: 64
  sensor_generator: 'LHS'  # AroundCylinder | LHS
  embedding_generator: 'Mask'  # Voronoi | Mask
  seed: 1

dataset_preloaded:
  train: true
  val: true
  test: true

architecture:
  n_channels: 2   # fixed for 2d problems
  embedding_dim: 64
  n_fno_layers: 4
  n_fno_modes: 24
  n_stacked_networks: 2
  from_checkpoint: null   # set to null to train from scratch

training:
  train_batch_size: 4
  val_batch_size: 2
  learning_rate: 1e-3
  a: 50.
  r: 0.01
  n_epochs: 100
  patience: 5
  tolerance: 0.
  save_frequency: 1

evaluate:
  from_checkpoint: '.checkpoints/epoch1.pt'

inference:
  case_dir: 'data/test/case0006'
  sensor_timeframes: [40, 45, 50, 55, 60]
  reconstruction_timeframes: [47]
  sensor_position_path: 'tensors/train/sensor_positions/pos.pt'
  from_checkpoint: '.checkpoints/epoch3.pt'



