dataset:
  init_sensor_timeframe_indices: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
  n_fullstate_timeframes_per_chunk: 10
  n_samplings_per_chunk: 1
  resolution: [140, 240]
  n_sensors: 32
  sensor_generator: 'AroundCylinder'  # AroundCylinder | LHS
  embedding_generator: 'Voronoi'      # Voronoi | Mask
  seed: 1

architecture:
  n_channels: 2
  n_afno_layers: 8
  embedding_dim: 2048
  block_size: 256
  dropout_rate: 0.1
  n_stacked_networks: 16
  from_checkpoint: null   # set to null to train from scratch

training:
  train_batch_size: 4
  val_batch_size: 2
  learning_rate: 5e-4
  a: 10.
  r: 0.01
  n_epochs: 1000
  patience: 50
  tolerance: 0.
  save_frequency: 1

predict:
  from_checkpoint: '.checkpoints/epoch10.pt'

