dataset:
  init_sensor_timeframes: [0, 5, 10, 15, 20]
  n_fullstate_timeframes_per_chunk: 1
  n_samplings_per_chunk: 1
  resolution: [140, 240]
  n_sensors: 32
  sensor_generator: 'LHS'  # AroundCylinder | LHS
  embedding_generator: 'Voronoi'  # Voronoi | Mask
  dropout_probabilities: [0.05, 0.04, 0.03, 0.02, 0.01]   # [] for no dropout
  seed: 1
  already_preloaded: false

architecture:
  branch_net: 'FNO'  # FNO | UNet
  n_channels: 2   # fixed for 2d problems
  embedding_dim: 64
  n_stacked_networks: 2
  # FNO-specific configs:
  n_fno_layers: 4
  n_hmodes: 24
  n_wmodes: 48

training:
  from_checkpoint: 'best_flronetfno/flronetfno13.pt'  # set to null to train from scratch
  train_batch_size: 4
  val_batch_size: 2
  learning_rate: 1e-4
  n_epochs: 100
  patience: 5
  tolerance: 0.
  save_frequency: 1
  freeze_branchnets: false
  freeze_trunknets: false
  freeze_bias: false

evaluate:
  from_checkpoint: 'best_flronetfno/flronetfno13.pt'
  n_dropout_sensors: 10
  already_preloaded: false

inference:
  case_dir: 'data/test/case0045'
  sensor_timeframes: [620, 625, 630, 635, 640]
  reconstruction_timeframes: [632.5]
  sensor_position_path: 'tensors/test/sensor_positions/pos.pt'
  n_dropout_sensors: 3
  from_checkpoint: 'best_flronetfno/flronetfno13.pt'
  # FNO-specific configs:
  out_resolution: [140, 240]
  # out_resolution: [280, 480]
  # out_resolution: [560, 960]
  # out_resolution: [1120, 1920]

