dataset:
  root: 'data'
  init_sensor_timeframe_indices: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
  n_fullstate_timeframes_per_chunk: 10
  n_samplings_per_chunk: 1
  resolution: [140, 240]
  n_sensors: 32
  sensor_generator: 'AroundCylinder'  # AroundCylinder | LHS
  embedding_generator: 'Voronoi'      # Voronoi | Mask
  seed: 1

architecture:
  embedding_dim: 1536
  n_layers: 12
  block_size: 384
  patch_size: [8, 8]
  dropout_rate: 0.
  from_checkpoint: null   # set to null to train from scratch

training:
  train_batch_size: 4
  val_batch_size: 2
  learning_rate: 5e-4
  n_epochs: 1000
  patience: 50
  tolerance: 0.
  save_frequency: 1

predict:
  ondate: '20240906'
  from_global_checkpoint: '.checkpoints/global/epoch55.pt'
  from_local_checkpoint: '.checkpoints/local/epoch20.pt'
  global_plot_resolution: null   # set to null to respect the true resolution
  local_plot_resolution: null   # set to null to respect the true resolution

